### ISSUE TITLE
Make script to automatically update completed problems

### ISSUE THREAD

**Issue by PhaseRush** [Prompt-ing/LeetCode-ing#53]
As a user, I would like to avoid having to update the completed problems list/table manually. It is an error prone action and takes time.

It would be nice to separate the list into a separate file, and be linked from the readme, to clearly separate the purposes of the files.

I propose a two stage change:

Firstly, one to write a script which can look at the src files for each language to determine what has been completed, then generate a corresponding table:

| Q# | Question name | Java | Python|
| --- | --- | --- | --- |
| 1 | [TwoSum](https://leetcode.com/problems/two-sum/) | [java1](https://github.com/LeetCube/LeetCube/blob/015e8322795395b0afb6ce45f54a691dceddaf7e/java/src/main/java/leetcube/phaserush/Code1.java#L7) | [py1](https://github.com/LeetCube/LeetCube/blob/015e8322795395b0afb6ce45f54a691dceddaf7e/python/src/code_1.py#L5) |

Then, as an optional second change, we would like to run the script (conditionally) for every PR to update the table.

**Comment by dataprob** [comment]
java and python got swapped in the table?

**Comment by PhaseRush** [comment]
> java and python got swapped in the table?

Whoops, fixed
