### ISSUE TITLE
Complete recommendations for following community standards

### ISSUE THREAD

**Issue by PhaseRush** [Prompt-ing/LeetCode-ing#55]
Github has a checklist for their recommendations for following community standards [here](https://github.com/LeetCube/LeetCube/community)

The checklist includes items such as having a README, License, etc. We're currently missing some items which I think we should add:

- [x] Contributing guidelines - we are being fast and loose with this and that's totally fine. Let's formalize our informality and document it
- [x] Issue templates - it would probably be helpful to make a standard template for those that want to use it. We can choose to not enforce it to lower the barrier to entry
- [x] PR template - same as above

As for the other items in the list, I don't think they provide that much value. Open for discussion.

**Comment by PhaseRush** [comment]
Btw, should we get rid of one of those "LeetCube Project"s?

**Comment by dataprob** [comment]
> Btw, should we get rid of one of those "LeetCube Project"s?

There's only 1 project rn, the other is template (don't delete it)

<img width="1047" alt="Screenshot 2023-06-06 at 12 33 03 AM" src="https://github.com/LeetCube/LeetCube/assets/86937926/ca7856db-2350-45d9-97a4-3301ac279d20">
